[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
monitor_encoding = UTF-8

lib_deps =
    https://github.com/adafruit/Adafruit_AHT10.git
    adafruit/Adafruit_Sensor @ ^1.1.14
